version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_app_container
    volumes:
      - .:/app
    working_dir: /app
    command: python3 app.py
    restart: unless-stopped
